{{- range $name, $_ := .Values.components }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    {{- include "operations-hub.labels" $ | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
